<?php
//
  // A71-BackUp 1.5 (15.01.2008) By Alessandro Marinuzzi [Alecos]
  // -> Copyright © 2007-2008 · Alessandro Marinuzzi [Alecos] <--
  //
  //  AUTHOR:
  //  ¯¯¯¯¯¯¯
  //  Alecos ->  Fullname: Alessandro Marinuzzi
  //             Address:  Via Torre Pilo n.14 /c
  //             City:     Palermo
  //             ZipCode:  90151
  //             Country:  Italy
  //
  //  E-Mail:    alecos@alecos.it
  //  Web:       http://www.alecos.it/
  //  A71-BackUp is FreeWare! A PayPal donation is welcome ! For making a donation
  //  visit my web site: http://www.alecos.it/
  //
  ###############################################################
  ############## Do not change the following code! ##############
  ###############################################################
//


// the following are the language definitions
define('HEADING_TITLE', 'Site Backup Generator');
define('WARNING_NOT_SECURE_FOR_DOWNLOADS','<span class="errorText">NOTE: You do not have SSL enabled. <br />Any downloads you do from this page will not be encrypted. <br />Doing backups will be fine, but download of files from the server presents a security risk.');
define('TABLE_HEADING_TITLE', 'This will Back Up ALL files on: ');
define('TABLE_HEADING_FILE_DATE', '<span class="errorText">NOTE: This does NOT BACK UP your database !!!!<br />Either run the Backup MYSQL Plugin and store it on the server PRIOR to running the Site Back Up <br />or run the Backup MYSQL Plugin and save locally along with the file generated by this script! 
');
define('TABLE_HEADING_FILE_SIZE', '');
define('TABLE_HEADING_ACTION', 'Do the Back Up');
?>